### PR TITLE
New feature and fix

### PR DESCRIPTION
**Pull request by vadim-on-github**
Enable user to set a gap between top/bottom of viewport and top/bottom of sidebar
Reposition the sidebar when viewport resizes preventing a unintentionally partially hidden or badly positioned sidebar
Add missing and new usage instructions in README, be more descriptive

### CODE REVIEW

**Comment by amerllica** [comment]
Dear @Krzysztof-Antosik please review this good PR. thanks.

**Comment by Krzysztof-Antosik** [comment]
I reviewed it and combined it, but I had to optimize it further and fix a few bugs

**Comment by vadim-on-github** [comment]
Thank you very much!

**Comment by Krzysztof-Antosik** [comment]
Would any more functions be needed here?

**Comment by vadim-on-github** [comment]
Nope! Think we're all good for now

**Pull request merged**
